### ISSUE TITLE
"Assigned to" shortcuts?

### ISSUE THREAD

**Issue by rleist** [markwragg/Powershell-Remedy#1]
Started playing with the Remedy REST API today from PowerrShell. Have you found any shortcuts in the API for specifying "assigned to me" or "assigned to my groups" filters?

**Comment by markwragg** [comment]
Sorry for taking so long to respond to this issue. Unfortunately I don't have access to a Remedy system any more so can't advise on this, if its not in the docs you probably want to raise with BMC themselves.
